// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu1c3BsJ414GT-WNlwzJUXTCtMPXPGuA4',
    appId: '1:818797512295:web:d873f21719f6fdfef8b6c2',
    messagingSenderId: '818797512295',
    projectId: 'itinventory-8e636',
    authDomain: 'itinventory-8e636.firebaseapp.com',
    storageBucket: 'itinventory-8e636.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxBcw9AURNUv4uS2N0__nMvriosvIG6Ro',
    appId: '1:818797512295:android:1fa3109193698ea1f8b6c2',
    messagingSenderId: '818797512295',
    projectId: 'itinventory-8e636',
    storageBucket: 'itinventory-8e636.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBemy4b8qT5KVTO2RVOwlBihYcYFYH6wpE',
    appId: '1:818797512295:ios:bd1d96fedf8cd530f8b6c2',
    messagingSenderId: '818797512295',
    projectId: 'itinventory-8e636',
    storageBucket: 'itinventory-8e636.appspot.com',
    iosBundleId: 'com.example.itinventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBemy4b8qT5KVTO2RVOwlBihYcYFYH6wpE',
    appId: '1:818797512295:ios:bd1d96fedf8cd530f8b6c2',
    messagingSenderId: '818797512295',
    projectId: 'itinventory-8e636',
    storageBucket: 'itinventory-8e636.appspot.com',
    iosBundleId: 'com.example.itinventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu1c3BsJ414GT-WNlwzJUXTCtMPXPGuA4',
    appId: '1:818797512295:web:efba78113e233e81f8b6c2',
    messagingSenderId: '818797512295',
    projectId: 'itinventory-8e636',
    authDomain: 'itinventory-8e636.firebaseapp.com',
    storageBucket: 'itinventory-8e636.appspot.com',
  );
}
